Goal: Understand matrices like an ML engineer.

### 1. Import NumPy

In [1]:
import numpy as np

### 2. Create a 2D Matrix

In [2]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 3. Check Matrix Shape

In [ ]:
print("Shape:", matrix.sha)

Shape: (3, 3)


### 4. Access Specific Elements

In [4]:
print(matrix[0, 0])
print(matrix[1, 2])

1
6


### 5. Matrix Slicing

In [7]:
print(matrix[0:2, 0:2])

[[1 2]
 [4 5]]


### 6. Create Fake Grayscale Image

In [8]:
fake_image = np.zeros((5, 5))
print(fake_image)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### 7. Modify a Region

In [9]:
fake_image[1:4, 1:4] = 255
print(fake_image)

[[  0.   0.   0.   0.   0.]
 [  0. 255. 255. 255.   0.]
 [  0. 255. 255. 255.   0.]
 [  0. 255. 255. 255.   0.]
 [  0.   0.   0.   0.   0.]]


### 8. Create Random Image Data

In [ ]:
# Format: np.random.randint(low, high, size)
random_image = np.random.randint(0, 256, (5, 5))
print(random_image)

[[ 84 213  70   1 182]
 [219  59 106 223 173]
 [245  60 238 243 196]
 [ 70  87 245 168 221]
 [237 106 232  56  25]]


### 📌 What We Learned

- Matrix = NumPy array
- Shape tells dimensions
- matrix[row, col] accesses values
- Slicing selects regions
- Images are just matrices
- Cropping = slicing
- Pixel modification = matrix editing